In [1]:
import numpy as np

In [2]:
# For first layer Z1=5x1, W1= 2x5, b1=5x1
np.random.seed(seed= 289)
x = np.array([[0.3], [0.4]])
W1 = np.random.rand(2,5)
b1= np.random.rand(5,1)
# You find the value of b1

In [3]:
b1

array([[0.48966863],
       [0.61544854],
       [0.62467448],
       [0.08738796],
       [0.90462271]])

In [4]:
z1 = np.dot(W1.transpose(),x)+b1      #Fill in the parantheses
a1 = 1/(1+np.exp(-z1))
a1

array([[0.70892956],
       [0.71899282],
       [0.70005254],
       [0.58846646],
       [0.80137956]])

In [5]:
# Design the second layer
# For first layer Z2=1x1, W2=5x1 , b2=1x1
np.random.seed(seed= 289)
W2 = np.random.rand(5,1)
b2 = np.random.rand(1,1)

In [6]:
z2 = np.dot(W2.transpose(),a1)+b2
a2 = 1/(1+np.exp(-z2))
a2

array([[0.9312211]])

From the results we can see that both sensors indicate a strong probability of flooding.